# NumPy Functionality Examples Lab - 1 

Reg.No : 21BCE1964

This Jupyter Notebook provides examples of major functionalities in the NumPy library.

In [1]:
# Importing NumPy
import numpy as np

## 1. Creating Arrays

### From a List

In [2]:
# Creating an array from a list
arr_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(arr_list)
print(arr_from_list)

[1 2 3 4 5]


### With Zeros

In [3]:
# Creating an array with zeros
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


### With Random Values

In [4]:
# Creating an array with random values
random_array = np.random.rand(3, 3)
print(random_array)

[[0.80544432 0.79560047 0.87107026]
 [0.14611407 0.61642723 0.6058481 ]
 [0.6014798  0.32368471 0.52761992]]


## 2. Array Operations

### Element-wise Addition

In [5]:
# Element-wise addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


### Mathematical Operations

In [6]:
# Mathematical operations
square_root = np.sqrt(arr1)
print(square_root)

[1.         1.41421356 1.73205081]


### Matrix Multiplication

In [7]:
# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)
print(matrix_product)

[[19 22]
 [43 50]]


## 3. Indexing and Slicing

### Indexing

In [8]:
# Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[2])  # Output: 3

3


### Slicing

In [9]:
# Slicing
sub_arr = arr[1:4]
print(sub_arr)  # Output: [2, 3, 4]

[2 3 4]


## 4. Statistical Operations

### Mean and Standard Deviation

In [10]:
# Mean and standard deviation
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
std_dev = np.std(data)
print(mean_value, std_dev)

3.0 1.4142135623730951


### Sum of Elements

In [11]:
# Sum of elements
total_sum = np.sum(data)
print(total_sum)

15


## 5. Linear Algebra

### Eigenvalues and Eigenvectors

In [12]:
# Eigenvalues and eigenvectors
matrix = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues, eigenvectors)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Singular Value Decomposition (SVD)

In [13]:
# Singular value decomposition (SVD)
U, S, V = np.linalg.svd(matrix)
print(U, S, V)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] [5.4649857  0.36596619] [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


## Bracket Indexing and Selection

### Basic Indexing

In [15]:
# Basic indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[2])  # Output: 3

3


### Slicing

In [16]:
# Slicing
sub_arr = arr[1:4]
print(sub_arr)  # Output: [2, 3, 4]

[2 3 4]


## Broadcasting

### Scalar Broadcasting

In [17]:
# Scalar broadcasting
arr += 2
print(arr)

[3 4 5 6 7]


### Element-wise Operations with Broadcasting

In [18]:
# Element-wise operations with broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## Indexing a 2D Array (Matrices)

### Creating a 2D Array

In [19]:
# Creating a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Indexing Elements in a 2D Array

In [20]:
# Indexing elements in a 2D array
element = matrix[1, 2]
print(element)  # Output: 6

6


### Slicing Rows and Columns

In [21]:
# Slicing rows and columns
row_slice = matrix[0:2, 1:3]
print(row_slice)

[[2 3]
 [5 6]]


## Selection based on Comparison Operators

### Boolean Indexing

In [22]:
# Boolean indexing
bool_arr = matrix > 5
selected_elements = matrix[bool_arr]
print(selected_elements)

[6 7 8 9]
